<?php
/**
 * $Id$
 * @file
 *   Install for amazon_store.module
 *
 */

function amazon_store_install() {
  drupal_install_schema('amazon_store');
}

function amazon_store_uninstall() {
  drupal_uninstall_schema('amazon_store');
}

function amazon_store_schema() {
  $schema['cache_amazon_store'] = drupal_get_schema_unprocessed('system', 'cache');
  $schema['cache_amazon_store']['description'] = 'Store amazon item data, keyed by ASIN.';

  return $schema;
}